### PR TITLE
new example: return json response with necessary headers

### PR DESCRIPTION
**Pull request by brianraila**

### CODE REVIEW

**Comment by brianraila** [comment]
This new example demonstrates how to return a JSON response with necessary headers.

**Comment by danteissaias** [comment]
This is unnecessary since `Response.json` exists. https://fetch.spec.whatwg.org/#dom-response-json

**Comment by danteissaias** [comment]
Alternatively you can return an object and fast will automatically run `Response.json` on it. https://github.com/danteissaias/fast/blob/704a073ad4dc48abb73f06f42f9ef165d5ea5b6f/tests.ts#L19

**Comment by brianraila** [comment]
Good stuff

**Pull request closed without merging**
