### PR TITLE
Add url query

### PR DESCRIPTION
**Pull request by omar2205**
This adds a query method to the Context class. `ctx.query['page']`

### CODE REVIEW

**Comment by danteissaias** [comment]
This causes a huge slowdown since `new URL()` would be called in the `Context` constructor.

```
cpu: Apple M1
runtime: deno 1.24.0 (aarch64-apple-darwin)

file:///Users/anon/repos/fast/bench.ts
benchmark               time (avg)             (min … max)       p75       p99      p995
---------------------------------------------------------- -----------------------------
app.handle          670.92 ns/iter   (644.25 ns … 1.55 µs) 651.66 ns   1.55 µs   1.55 µs
app.handle (PR #6)    2.55 µs/iter    (2.25 µs … 307.5 µs)   2.42 µs   5.75 µs   7.67 µs
```

**Comment by omar2205** [comment]
Yeah, I just ran the benchmarks after I opened the PR.

**Comment by danteissaias** [comment]
Store it in a private value so that you don't need to run `Object.fromEntries` on every access.

**Comment by omar2205** [comment]
Sorry, IDK what you mean by that. Don't use JS classes that much.

**Comment by omar2205** [comment]
Awesome!

**Pull request merged**
